name: signet-server

services:
  mainchain:
    healthcheck:
     test: ["CMD", "drivechain-cli", "-rpcuser=user", "-rpcpassword=password", "-signet", "getblockchaininfo"]

    image: ghcr.io/layertwo-labs/bitcoin-patched:sha-c169c54
    # map the named volume to the data directory
    volumes: [mainchain-data:/home/drivechain/.drivechain]
    restart: unless-stopped
    ports:
      - "38333:38333" # P2P, exposed to the internet
      - "127.0.0.1:38332:38332" # RPC, only available from host machine
    command:
      - drivechaind
      - -rpcuser=user
      - -rpcpassword=password
      - -server
      - -signet
      - -signetblocktime=60
      - -signetchallenge=00141551188e5153533b4fdd555449e640d9cc129456
      - -acceptnonstdtxn
      - -listen
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -txindex
      - -fallbackfee=0.00021
      - -zmqpubsequence=tcp://0.0.0.0:29000

  # TODO: we're connecting to the default drivechain.live `electrs` instance. 
  # Run one as part of this infra stack?
  enforcer: 
    image: ghcr.io/layertwo-labs/bip300301_enforcer:pr-136  
    restart: unless-stopped
    # Uncomment these lines to adjust the RUST_LOG (or any other!) env var
    environment: 
      RUST_LOG: trace,h2=info,hyper_util=info

    healthcheck:
       test: ["CMD", "grpc_health_probe", "-service=cusf.mainchain.v1.ValidatorService", "-addr=localhost:50051"]

    volumes: [enforcer-data:/root/.local/share/bip300301_enforcer]
    ports: 
      - "127.0.0.1:50051:50051" # gRPC, only available from host machine
      - "127.0.0.1:8122:8122" # JSON-RPC, only available from host machine

    command:
      - --node-rpc-addr=mainchain:38332
      - --node-rpc-user=user
      - --node-rpc-pass=password
      - --serve-grpc-addr=0.0.0.0:50051 # Expose over 0.0.0.0 so that other services can connect to it
      - --serve-rpc-addr=0.0.0.0:8122 # Expose over 0.0.0.0 so that other services can connect to it
      - --node-zmq-addr-sequence=tcp://mainchain:29000
      - --enable-wallet
      - --enable-mempool
      - --wallet-auto-create
      - --log-level=trace
  
  # TODO: must make the seed work... Either:
  # --mnemonic-seed-phrase-path and a file path
  # or a RPC 
  thunder:
    healthcheck:
      test: ["CMD", "thunder_app_cli", "balance"]
    image: ghcr.io/layertwo-labs/thunder:sha-3796e65
    restart: unless-stopped
    volumes: [thunder-data:/root/.local/share/thunder]
    ports: 
      - "4009:4009" # P2P, exposed to the internet
      - "127.0.0.1:6009:6009" # RPC, only available from host machine

    entrypoint: 
       - thunder_app
       - --headless
       - --mainchain-grpc-address=http://enforcer:50051
       - --rpc-addr=0.0.0.0:6009

  buf:
    # Assign this to a special profile, so that `docker compose up` doesn't execute it. 
    profiles: [cli]
    image: bufbuild/buf

volumes: 
  mainchain-data:
  enforcer-data:
  thunder-data:

