# This Compose configuration is intended as a base for other Compose configurations.

services:
  mainchain:
    healthcheck:
      test:
        [
          "CMD",
          "drivechain-cli",
          "-rpccookiefile=/cookie",
          "-chain=${NETWORK}",
          "getblockchaininfo",
        ]

    secrets:
      # Create a file with one or more `rpcauth` lines. Allows for specifying
      # multiple different users, such that different services can have different
      # credentials.
      - source: bitcoind-${NETWORK}-rpcauth.conf
        target: /rpcauth.conf

      - source: bitcoind-${NETWORK}-cookie
        target: /cookie

    image: ghcr.io/layertwo-labs/bitcoin-patched:sha-32e384a
    restart: unless-stopped
    ports:
      - "38333:38333" # P2P, exposed to the internet
      - "127.0.0.1:38332:38332" # RPC, only available from host machine
    command:
      - drivechaind
      - -debug=rpc
      - -conf=/rpcauth.conf
      - -server
      - -chain=${NETWORK}
      - -signetchallenge=${SIGNET_CHALLENGE:-""}
      - -acceptnonstdtxn
      - -listen
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -txindex
      - -fallbackfee=0.00021
      - -zmqpubsequence=tcp://0.0.0.0:29000
      - -rest

  enforcer:
    image: ghcr.io/layertwo-labs/bip300301_enforcer:pr-290
    pull_policy: always
    restart: unless-stopped
    environment:
      RUST_LOG: debug,h2=info,hyper_util=info
      RUST_BACKTRACE: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

    healthcheck:
      test:
        [
          "CMD",
          "grpc_health_probe",
          "-service=cusf.mainchain.v1.ValidatorService",
          "-addr=localhost:50051",
        ]

    volumes: [enforcer-data:/root/.local/share/bip300301_enforcer]
    ports:
      - "127.0.0.1:${ENFORCER_SERVE_GRPC_PORT}:${ENFORCER_SERVE_GRPC_PORT}" # gRPC, only available from host machine
      - "127.0.0.1:${ENFORCER_SERVE_RPC_PORT}:${ENFORCER_SERVE_RPC_PORT}" # JSON-RPC, only available from host machine

    command:
      - --log-format=json
      - --log-level=trace
      - --node-rpc-addr=${CORE_RPC_ADDR}
      - --node-rpc-cookie-path=/daemon-dir/.cookie
      - --serve-grpc-addr=0.0.0.0:${ENFORCER_SERVE_GRPC_PORT} # Expose over 0.0.0.0 so that other services can connect to it
      - --serve-rpc-addr=0.0.0.0:${ENFORCER_SERVE_RPC_PORT} # Expose over 0.0.0.0 so that other services can connect to it
      - --node-zmq-addr-sequence=${CORE_ZMQ_ADDR_SEQUENCE}
      - --enable-wallet
      - --enable-mempool
      - --wallet-auto-create
      - --wallet-skip-periodic-sync
      # mainchain Bitcoin Core address
      - --signet-miner-coinbase-recipient=${SIGNET_MINER_COINBASE_RECIPIENT:-""}
      - --wallet-electrum-host=electrs
      - --wallet-electrum-port=50001
      - --wallet-sync-source=electrum
      - --wallet-esplora-url=http://127.0.0.1:3000

  bitassets:
    image: ghcr.io/layertwo-labs/bitassets:sha-8f8a627
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "plain_bitassets_app_cli", "balance"]
    # Bitassets uses the same networking stack as thunder, so doing the
    # same thing here.
    network_mode: host
    volumes:
      - bitassets-data:/root/.local/share/plain_bitassets
      - logs-data:/logs

    command:
      - --headless
      - --log-level=trace
      - --mainchain-grpc-host=0.0.0.0
      # For BitAssets to be reachable from other containers (via host-gateway) ,
      # we need to bind to 0.0.0.0. This means that the host machine needs to
      # make sure to /not/ expose this to the open internet!
      - --net-addr=0.0.0.0:4004
      - --rpc-host=0.0.0.0
      - --rpc-port=6004
      - --zmq-addr=0.0.0.0:28004

  bitnames:
    image: ghcr.io/layertwo-labs/bitnames:sha-2a9fd14
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "plain_bitnames_app_cli", "balance"]
    # Bitnames uses the same networking stack as thunder, so doing the
    # same thing here.
    network_mode: host
    volumes:
      - bitnames-data:/root/.local/share/plain_bitnames
      - logs-data:/logs

    command:
      - --headless
      - --log-level=trace
      - --mainchain-grpc-host=0.0.0.0
      - --mainchain-grpc-port=50051
        # For Thunder to be reachable from other containers (via host-gateway) ,
        # we need to bind to 0.0.0.0. This means that the host machine needs to
        # make sure to /not/ expose this to the open internet!
      - --net-addr=0.0.0.0:4002
      - --rpc-addr=0.0.0.0:6002
      - --zmq-addr=0.0.0.0:28002

  photon:
    image: ghcr.io/layertwo-labs/photon:sha-13ba3e4
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "photon_app_cli", "balance"]
    network_mode: host
    volumes:
      - photon-data:/data
      - logs-data:/logs
    command:
      - --datadir=/data
      - --log-dir=/logs/photon
      - --log-level=trace
      - --headless
      - --mainchain-grpc-url=http://localhost:50051
      - --net-addr=0.0.0.0:4099
      - --rpc-addr=0.0.0.0:6099
      - --network=${NETWORK}

  # TODO: must make the seed work... Either:
  # --mnemonic-seed-phrase-path and a file path
  # or a RPC
  thunder:
    # Cannot get UDP to play well with Docker. Unable to connect external
    # nodes to this one through the open internet. Works when running with
    # host mode!
    network_mode: host
    healthcheck:
      test:
        ["CMD", "thunder_app_cli", "--rpc-url=http://127.0.0.0:6009", "balance"]
    image: ghcr.io/layertwo-labs/thunder:sha-61cbd03
    restart: unless-stopped
    volumes:
      - thunder-data:/root/.local/share/thunder
      - logs-data:/logs
    # As long as we're running the container using the `host` network mode,
    # these are discarded.
    # ports:
    #  - "4009:4009/udp" # P2P, exposed to the internet, over UDP
    #  - "127.0.0.1:6009:6009" # RPC, only available from host machine

    entrypoint:
      - thunder_app
      - --headless
      - --mainchain-grpc-url=http://localhost:50051
      # For Thunder to be reachable from other containers (via host-gateway) ,
      # we need to bind to 0.0.0.0. This means that the host machine needs to
      # make sure to /not/ expose this to the open internet!
      - --rpc-addr=0.0.0.0:6009
      - --log-level=trace
      - --log-level-file=trace
      - --log-dir=/logs/thunder

  coinshift:
    image: ghcr.io/layertwo-labs/coinshift:sha-9eeb5b2
    # See network comment on the thunder service
    network_mode: host
    restart: unless-stopped
    volumes:
      - coinshift-data:/root/.local/share/coinshift
      - logs-data:/logs
    healthcheck:
      test:
        [
          "CMD",
          "coinshift_app_cli",
          "--rpc-url=http://localhost:6255",
          "get-blockcount",
        ]
    command:
      - --headless
      - --net-addr=0.0.0.0:4255
      - --rpc-addr=0.0.0.0:6255
      - --mainchain-grpc-url=http://localhost:50051
      - --log-dir=/logs/thunder
      - --log-level=trace
      - --log-level-file=trace
      - --network=${NETWORK}

  zside:
    image: ghcr.io/iwakura-rein/thunder-orchard:sha-7e34625
    restart: unless-stopped
    # Cannot get UDP to play well with Docker. Unable to connect external
    # nodes to this one through the open internet. Works when running with
    # host mode!
    network_mode: host
    healthcheck:
      test:
        [
          "CMD",
          "thunder_orchard_app_cli",
          "--rpc-url=http://127.0.0.0:6098",
          "balance",
        ]
    # TODO: adjust this once we can move away from network_mode: host
    # ports: [4098:4098/udp] # P2P
    volumes:
      - zside-data:/root/.local/share/thunder-orchard
      - logs-data:/logs
    command:
      - --headless
      - --mainchain-grpc-url=http://localhost:50051
      - --rpc-addr=0.0.0.0:6098
      - --log-level=trace
      - --log-level-file=trace
      - --log-dir=/logs/zside

  mempool-db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "mempool",
          "-pmempool",
        ]
    image: mariadb:10.5.21
    restart: unless-stopped
    stop_grace_period: 1m
    volumes: [mysql-data:/var/lib/mysql]

  mempool-web:
    environment:
      FRONTEND_HTTP_PORT: 8080
      BACKEND_MAINNET_HTTP_HOST: mempool-api
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
    image: mempool/frontend:v3.2.1
    restart: unless-stopped
    stop_grace_period: 1m
    command:
      "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 8080:8080 # should be reachable externally

  mempool-api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: [mempool-db]

    # conf: https://github.com/mempool/mempool/blob/e3c3f31ddbf9543db12ef4f7e5032566757d31f9/backend/mempool-config.sample.json#
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: electrs
      ELECTRUM_PORT: 50001
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: mainchain
      CORE_RPC_PORT: 38332
      CORE_RPC_COOKIE: true
      CORE_RPC_COOKIE_PATH: "/daemon-dir/.cookie"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
      FIAT_PRICE_ENABLED: false

    # 'latest' is on an ancient version
    image: mempool/backend:v3.2.1
    restart: unless-stopped
    stop_grace_period: 1m
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8999/api/v1/backend-info"]
    command:
      "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
    volumes: [mempool-api-data:/backend/cache]

  # The other electrs instance we have running is mempool/electrs, not romanz/electrs.
  # The first is a fork of a fork of the original romanz/electrs implementation. It
  # turns out that BlueWallet doesn't work with mempool/electrs. We therefore run two
  # instances! mempool/electrs is used for the block explorer, and romanz/electrs is
  # used for BlueWallet. The resource requirements for romanz/electrs are much lower,
  # only a few dozen gigs of storage.
  romanzelectrs:
    build: https://github.com/romanz/electrs.git#66b1de65c0afffff19ea97be9b872e488e4d6778
    secrets:
      - source: bitcoind-${NETWORK}-cookie
        target: /daemon-dir/.cookie
    volumes:
      - romanz-electrs-data:/app
    extra_hosts: ["host.docker.internal:host-gateway"]
    restart: unless-stopped
    command:
      - electrs
      - --db-dir=/app/db
      - --cookie-file=/daemon-dir/.cookie
      - --daemon-rpc-addr=${CORE_RPC_ADDR}
      - --daemon-p2p-addr=${CORE_P2P_ADDR}
      - --electrum-rpc-addr=0.0.0.0:50001
      - --log-filters=debug
      - --network=${NETWORK}
      - --magic=${NETWORK_MAGIC}

  # TODO: how do we enable SSL here?
  electrs:
    image: mempool/electrs
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/blocks/tip/height"]
    environment:
      RUST_BACKTRACE: 1

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped
    # The Electrum port is left out here because we instead want to expose the
    # 50001 port from the romanzelectrs service.
    ports:
      - 3000:3000 # Esplora REST API

    volumes: [electrs-data:/app/db]

    # https://github.com/Blockstream/esplora?tab=readme-ov-file#how-to-run-the-explorer-for-bitcoin-mainnet
    command:
      - -vvv # pretty verbose logging
      - --timestamp
      # it's not possible to configure the cookie path, but it is possible to configure
      # the daemon directory. The cookie then needs to be mounted in as a secret into
      # the correct location.
      - --daemon-dir=/daemon-dir
      - --daemon-rpc-addr=${CORE_RPC_ADDR}
      - --jsonrpc-import
      - --db-dir=/app/db
      - --network=${NETWORK}
      - --http-addr=0.0.0.0:3000
      - --electrum-rpc-addr=0.0.0.0:50001
      - --electrum-txs-limit=30000
      - --cors=*

  fast-withdraw-server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    secrets:
      - source: bitcoind-${NETWORK}-cookie
        target: /daemon-dir/.cookie
    environment:
      BITCOIN_RPC_COOKIE_FILE: /daemon-dir/.cookie
      BITCOIN_RPC_URL: http://${CORE_RPC_ADDR}
      THUNDER_RPC_URL: http://host.docker.internal:6009
      BITNAMES_RPC_URL: http://host.docker.internal:6002
      PORT: 3333
      HOST: 0.0.0.0

    ports:
      - 127.0.0.1:3333:3333

    image: ghcr.io/layertwo-labs/fast-withdraw-server:sha-63aaa2f

  faucet-backend:
    restart: unless-stopped
    # Find image-tags here: https://github.com/LayerTwo-Labs/faucet-backend/pkgs/container/faucet-backend
    image: ghcr.io/layertwo-labs/faucet-backend:sha-daba7d4
    pull_policy: always
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "-H",
          "Content-Type: application/json",
          "-X",
          "POST",
          "localhost:8082/faucet.v1.FaucetService/ListClaims",
        ]
    ports:
      - 8082:8082
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - source: bitcoind-${NETWORK}-cookie
        target: /daemon-dir/.cookie
    command:
      - faucetd
      - --bitcoincore.address=${CORE_RPC_ADDR}
      - --bitcoincore.cookie=/daemon-dir/.cookie
      - --enforcer.url=http://enforcer:50051
      - --bitnames.url=http://host.docker.internal:6002
      - --bitassets.url=http://host.docker.internal:6004
      - --thunder.url=http://host.docker.internal:6009
      - --zside.url=http://host.docker.internal:6098
      - --coinshift.url=http://host.docker.internal:6255
      - --photon.url=http://host.docker.internal:6099
      - --listen=0.0.0.0:8082

  faucet-frontend:
    ports:
      - 3003:3003
    environment:
      API_BASE_URL: http://faucet-backend:8082
      METADATA_BASE_URL: https://node.${NETWORK}.drivechain.info
    pull_policy: always
    # We want to avoid specifying tags for both signet and forknet by themselves, so we
    # try to be a bit clever here. Perhaps too clever? Anyways: COMPOSE_PROJECT_NAME can
    # interpolated into the image name, and this is automatically set when running. This
    # means that we don't have to provide a .env file, or specify an env var on the
    # command line.
    # Find image-tags here:
    #   Signet: https://github.com/LayerTwo-Labs/faucet-frontend-signet-server/pkgs/container/faucet-frontend
    #   Forknet: https://github.com/LayerTwo-Labs/faucet-frontend-forknet-server/pkgs/container/faucet-frontend
    image: ghcr.io/layertwo-labs/faucet-frontend-${NETWORK}-server:sha-daba7d4

  # Can be used to run a container with the same volumes as the other services.
  # $ docker compose run --rm busybox sh

  # Todays Thunder logs:
  #   $ docker compose run --rm busybox cat /logs/thunder/$(date +%Y-%m-%d).log | lnav
  busybox:
    profiles: [cli]
    image: busybox
    volumes:
      - mainchain-data:/mainchain-data
      - enforcer-data:/enforcer-data
      - thunder-data:/thunder-data
      - zside-data:/zside-data
      - logs-data:/logs

  buf:
    # Assign this to a special profile, so that `docker compose up` doesn't execute it.
    #
    # Usage:
    #   $ docker compose run --rm buf curl --emit-defaults --protocol grpc --http2-prior-knowledge --list-methods http://enforcer:50051
    #   $ docker compose run --rm buf curl --emit-defaults --protocol grpc --http2-prior-knowledge http://enforcer:50051/cusf.mainchain.v1.ValidatorService/GetChainTip
    profiles: [cli]
    image: bufbuild/buf

volumes:
  mainchain-data:
  enforcer-data:
  thunder-data:
  zside-data:
  bitassets-data:
  bitnames-data:
  electrs-data:
  romanz-electrs-data:
  logs-data:
  mysql-data:
  mempool-api-data:
  coinshift-data:
  photon-data:
