name: forknet-server

services:
  enforcer:
    profiles:
      - forknet

    secrets:
      - source: bitcoind-forknet-cookie
        target: /daemon-dir/.cookie

  mempool-db:
    profiles:
      - forknet

  mempool-web:
    profiles:
      - forknet

  mempool-api:
    profiles:
      - forknet
    secrets:
      - source: bitcoind-forknet-cookie
        target: /daemon-dir/.cookie

    environment:
      MEMPOOL_NETWORK: mainnet
      CORE_RPC_HOST: host.docker.internal
      CORE_RPC_PORT: 18301

  # The other electrs instance we have running is mempool/electrs, not romanz/electrs.
  # The first is a fork of a fork of the original romanz/electrs implementation. It
  # turns out that BlueWallet doesn't work with mempool/electrs. We therefore run two
  # instances! mempool/electrs is used for the block explorer, and romanz/electrs is
  # used for BlueWallet. The resource requirements for romanz/electrs are much lower,
  # only a few dozen gigs of storage.
  romanzelectrs:
    build: https://github.com/romanz/electrs.git#66b1de65c0afffff19ea97be9b872e488e4d6778
    profiles:
      - forknet
    secrets:
      - source: bitcoind-forknet-cookie
        target: /daemon-dir/.cookie
    # network_mode: host # network issues with P2P protocol?
    volumes:
      - romanz-electrs-forknet-data:/app
    extra_hosts: ["host.docker.internal:host-gateway"]
    restart: unless-stopped
    ports:
      - 50001:50001 # Electrum port
    command:
      - electrs
      - --db-dir=/app/db
      - --cookie-file=/daemon-dir/.cookie
      - --daemon-rpc-addr=host.docker.internal:18301
      - --daemon-p2p-addr=host.docker.internal:8300
      - --electrum-rpc-addr=0.0.0.0:50001
      - --log-filters=info
      - --magic=62333030

  electrs:
    profiles:
      - forknet
    volumes:
      # Mount this into something different from the baseline
      # Compose file, otherwise we'll overwrite our own mount
      - electrs-forknet-data:/forknet
    secrets:
      - source: bitcoind-forknet-cookie
        target: /daemon-dir/.cookie

    command:
      - -vv # pretty verbose logging
      - --timestamp
      - --daemon-rpc-addr=host.docker.internal:18301
      - --jsonrpc-import
      - --db-dir=/forknet/db
      - --daemon-dir=/daemon-dir
      - --network=mainnet
      - --http-addr=0.0.0.0:3000
      - --electrum-rpc-addr=0.0.0.0:50001
      - --electrum-txs-limit=30000
      - --cors=*

  faucet-backend:
    profiles:
      - forknet
    secrets:
      - source: bitcoind-forknet-cookie
        target: /cookie
    command:
      - faucetd
      - --bitcoincore.address=host.docker.internal:18301
      - --bitcoincore.cookie=/cookie
      - --enforcer.url=http://enforcer:50051
      - --listen=0.0.0.0:8082

  faucet-frontend:
    profiles:
      - forknet
    environment:
      API_BASE_URL: http://faucet-backend:8082
      METADATA_BASE_URL: https://node.forknet.drivechain.info

  busybox:
    volumes:
      - electrs-forknet-data:/electrs-forknet-data

# Paths to secrets refer to the (remote) host machine.
secrets:
  # IMPORTANT: this needs to be a file WITHOUT a trailing newline
  bitcoind-forknet-cookie:
    file: /data/secrets/bitcoind-forknet-cookie.txt

  bitcoind-forknet-rpcauth.conf:
    file: /data/secrets/bitcoind-forknet-rpcauth.conf

volumes:
  # Paths in volume mounts work poorly with remote Docker contexts.
  # We therefore specify external volumes. These can be created with
  # the following command on the machine hosting the Docker context:
  # $ docker volume create \
  #  --driver local --opt type=none \
  #  --opt o=bind --opt device=/data/electrs \
  #  electrs-forknet-data
  electrs-forknet-data:
    external: true
  romanz-electrs-forknet-data:
    external: true
